name: Robot Framework Tests WEB
 
on: push
 
jobs:
  test_web:
    name: Web Tests - Robot
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: https://jvluzc.github.io/ronbugado-academy12.2-front-robot/report.html

    steps:
      - name: Clonando para o Repositorio na Maquina Virtual
        uses: actions/checkout@v4
 
      - name: Instalação do Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
 
      - name: Instalando Chrome e ChromeDriver
        run: |
          # Instalar uma versão específica do Chrome
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_131.0.6778.69-1_amd64.deb
          sudo apt-get install -y ./google-chrome-stable_131.0.6778.69-1_amd64.deb
          rm ./google-chrome-stable_131.0.6778.69-1_amd64.deb
      
          # Identificar a versão do Chrome e instalar o ChromeDriver correspondente
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f 1)
          DRIVER_VERSION=$(wget -qO- https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION})
          wget https://chromedriver.storage.googleapis.com/${DRIVER_VERSION}/chromedriver_linux64.zip || exit 1
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          rm chromedriver_linux64.zip
      
          # Verificar versões instaladas
          google-chrome --version
          chromedriver --version
 
      - name: Instalação das depedências do Projeto
        run: |
          pip install setuptools
          pip install robotframework
          pip install robotframework-seleniumlibrary
 
      - name: Executando os testes Web do Robot
        run: |
          robot --outputdir results/ tests/

      - name: Salvando o Report dos Testes
        uses: actions/upload-artifact@v4
        with:
          name: robot-framework-report
          path: results/

      - name: Setup Pages
        uses: actions/configure-pages@v5
 
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: results/
 
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
